name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.13.0'

      - name: Build Package
        run: |
          corepack enable
          yarn --immutable
          yarn workspace cordis-landscape build
        shell: bash

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          external_repository: cordis-bot/landscape
          publish_branch: main
          publish_dir: packages/landscape/dist
          force_orphan: true
          enable_jekyll: true
          commit_message: '[skip ci] deploy'
